# Generated by Django 5.0.4 on 2024-05-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
