# Generated by Django 5.0.4 on 2024-05-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_enrollment_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.instructor')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.schoolyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.semester')),
            ],
            options={
                'unique_together': {('course', 'instructor', 'school_year', 'semester')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.class'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'enrolled_class')},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
    ]
